### HTML Parser - Part 1

In [6]:
from html.parser import HTMLParser

In [7]:
# create a subclass and override the handler methods
class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):        
        print ('Start :', tag)
        for ele in attrs:
            print ('->', ele[0], '>', ele[1])
            
    def handle_endtag(self, tag):
        print ('End   :', tag)
        
    def handle_startendtag(self, tag, attrs):
        print ('Empty :', tag)
        for ele in attrs:
            print ('->', ele[0], '>', ele[1])

In [10]:
# instantiate the parser and fed it some HTML
parser = MyHTMLParser()
parser.feed(''.join([input().strip() for _ in range(int(input()))]))
parser.close()

2
<html><head><title>HTML Parser - I</title></head>
<body data-modal-target class='1'><h1>HackerRank</h1><br /></body></html>
Start : html
Start : head
Start : title
End   : title
End   : head
Start : body
-> data-modal-target > None
-> class > 1
Start : h1
End   : h1
Empty : br
End   : body
End   : html


### HTML Parser - Part 2

In [1]:
from html.parser import HTMLParser

In [3]:
class MyHTMLParser(HTMLParser):
    def handle_comment(self,data):
        if('\n' in data):
            print(">>> Multi-line Comment")
        else:
            print(">>> Single-line Comment")
        print(data)
    def handle_data(self,data):
        if(data != '\n'):
            print(">>> Data")
            print(data)

In [4]:
html = ""
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'

4
<!--[if IE 9]>IE9-specific content
<![endif]-->
<div> Welcome to HackerRank</div>
<!--[if IE 9]>IE9-specific content<![endif]-->


In [5]:
parser = MyHTMLParser()
parser.feed(html)
parser.close()

>>> Multi-line Comment
[if IE 9]>IE9-specific content
<![endif]
>>> Data
 Welcome to HackerRank
>>> Single-line Comment
[if IE 9]>IE9-specific content<![endif]


### Detect HTML Tags, Attributes and Attribute Values

In [9]:
from html.parser import HTMLParser

In [12]:
# create a subclass and override the handler methods
class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):        
        print (tag)
        for ele in attrs:
            print ('->', ele[0], '>', ele[1])

    def handle_startendtag(self, tag, attrs):
        print (tag)
        for ele in attrs:
            print ('->', ele[0], '>', ele[1])

In [13]:
# instantiate the parser and fed it some HTML
parser = MyHTMLParser()
parser.feed(''.join([input().strip() for _ in range(int(input()))]))
parser.close()

head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


### Validating UID

In [14]:
import re

In [19]:
regex_uid = r"^(?=(?:[a-z\d]*[A-Z]){2})(?=(?:\D*\d){3})(?:([a-zA-Z\d])(?!.*\1)){10}$"

In [20]:
emp_uid = []
for _ in range(int(input())):
    emp_uid.append(input().strip())

2
B1CD102354
B1CDEF2354


In [21]:
for uid in emp_uid:
    if re.match(regex_uid, uid):
        print('Valid')
    else:
        print('Invalid')

Invalid
Valid


### Validating Credit Card Numbers

In [22]:
import re

In [28]:
pattern = re.compile(
    r'^'
    r'(?!.*(\d)(-?\1){3})'
    r'[456]\d{3}'
    r'(?:-?\d{4}){3}'
    r'$')

In [25]:
credit_cards = []
for _ in range(int(input())):
    credit_cards.append(input().strip())

6
4123456789123456
5123-4567-8912-3456
61234-567-8912-3456
4123356789123456
5133-3367-8912-3456
5123 - 3567 - 8912 - 3456


In [29]:
for card_number in credit_cards:
    print('Valid' if pattern.search(card_number) else 'Invalid')

Valid
Valid
Invalid
Valid
Invalid
Invalid


### Validating Postal Codes

In [31]:
import re

In [32]:
P = input()

110000


In [50]:
regex_integer_in_range = r"^([1-9][0-9]{5})$"   # Do not delete 'r'.
regex_alternating_repetitive_digit_pair = r"(?=(\d)\d\1)"   # Do not delete 'r'.

In [52]:
if bool(re.match(regex_integer_in_range, P)) and (len(re.findall(regex_alternating_repetitive_digit_pair, P)) < 2):
    print(True)
else:
    print(False)

False


In [58]:
S="25351"
re.search(regex_alternating_repetitive_digit_pair, S)

<re.Match object; span=(1, 1), match=''>

### Matrix Script

In [ ]:
import re

In [84]:
n, m = input().split(' ')

7 3


In [93]:
lines = []
for _ in range(int(n)):
    lines.append([c for c in input()])

Tsi
h%x
i #
sM 
$a 
#t%
ir!


In [97]:
lines

[['T', 's', 'i'],
 ['h', '%', 'x'],
 ['i', ' ', '#'],
 ['s', 'M', ' '],
 ['$', 'a', ' '],
 ['#', 't', '%'],
 ['i', 'r', '!']]

In [94]:
messasge = ""
for x in zip(*lines):
    column = ''.join(x)
    messasge += re.sub(r"[!@#$%&]", " ", column)

print(re.sub(r"\s{2,}", " ", messasge))

This is Matrix 


In [ ]:
# Another approach
#!/bin/python3

import math
import os
import random
import re
import sys

first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

matrix = []

for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)

lines = []
for _ in range(int(n)):
    lines.append([c for c in matrix])

matrix = list(zip(*matrix))
sample = str()
    
for words in matrix:
    for char in words:
        sample += char
           
print(re.sub(r'(?<=\w)([^\w\d]+)(?=\w)', ' ', sample))

### Map and Lambda Function

In [100]:
cube = lambda x: x**3

In [109]:
def fibonacci(n):
    fib_list = [0,1]
    
    for i in range(2,n):
        fib_list.append(fib_list[i-2] + fib_list[i-1])
        
    return(fib_list[:n])

In [110]:
print(list(map(cube, fibonacci(15))))

[0, 1, 1, 8, 27, 125, 512, 2197, 9261, 39304, 166375, 704969, 2985984, 12649337, 53582633]


### Validating Email Addresses With a Filter

In [129]:
import re

In [189]:
def fun(s):
    email_regex = r"^[\w-]+@[a-zA-Z\d]+\.[a-zA-Z]{1,3}$"
    if re.match(email_regex, s):
        return True
    else:
        return False

In [190]:
def filter_mail(emails):
    return list(filter(fun, emails))

In [191]:
emails = ['lara@hackerrank.com', 'brian-23@hackerrank.com', 'britts_54@hackerrank.com']

In [192]:
filter_mail(emails)

['lara@hackerrank.com', 'brian-23@hackerrank.com', 'britts_54@hackerrank.com']

### Reduce Function

In [193]:
from fractions import Fraction
from functools import reduce

In [197]:
def product(fracs):
    t = reduce(lambda x, y : x * y, fracs)
    return t.numerator, t.denominator

In [198]:
if __name__ == '__main__':
    fracs = []
    for _ in range(int(input())):
        fracs.append(Fraction(*map(int, input().split())))
    result = product(fracs)
    print(*result)

3
1 2
3 4
10 6
5 8


### XML 1 - Find the Score

In [199]:
import xml.etree.ElementTree as etree

In [225]:
xml = []
for _ in range(int(input())):
    xml.append(input())
    
xml = ''.join(xml)

6
<feed xml:lang='en'>
<title>HackerRank</title>
<subtitle lang='en'>Programming challenges</subtitle>
<link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
<updated>2013-12-25T12:00:00</updated>
</feed>


In [232]:
tree = etree.ElementTree(etree.fromstring(xml))

In [233]:
root = tree.getroot()

In [236]:
len(root)

5

In [240]:
def get_attr_number(node):
    score = len(node.attrib)

    for r in node:
        print(r.tag)
        score += get_attr_number(r)

    return score

In [241]:
get_attr_number(root)

title
subtitle
link
updated
entry
author
question
description


8

In [242]:
# Another approach

def get_attr_number(node):
    return len(node.attrib) + sum(get_attr_number(child) for child in node)

### XML2 - Find the Maximum Depth

In [243]:
import xml.etree.ElementTree as etree

In [254]:
xml = []
for _ in range(int(input())):
    xml.append(input())
    
xml = ''.join(xml)

6
<feed xml:lang='en'>
<title>HackerRank</title>
<subtitle lang='en'>Programming challenges</subtitle>
<link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
<updated>2013-12-25T12:00:00</updated>
</feed>


In [255]:
maxdepth = 0
def depth(elem, level):
    global maxdepth
    if (level == maxdepth):
        maxdepth += 1
        
    for child in elem:
        depth(child, level + 1)

In [256]:
tree = etree.ElementTree(etree.fromstring(xml))
depth(tree.getroot(), -1)
print(maxdepth)

1


### Standardize Mobile Number Using Decorators

In [325]:
def wrapper(f):
    def fun(l):
        f(['+91 '+x[-10:-5]+' '+x[-5:] for x in l])
    return fun

In [326]:
@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

In [323]:
l = [input() for _ in range(int(input()))]
print(l)

3
09191919191
9100256236
+919593621456


['09191919191', '9100256236', '+919593621456']

In [327]:
sort_phone(l)

+91 91002 56236
+91 91919 19191
+91 95936 21456


### Decorators 2 - Name Directory

In [339]:
import operator

In [368]:
def person_lister(f):
    def inner(people):
        return map(f, sorted(people, key=lambda x: int(x[2])))
    return inner

In [369]:
@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

In [336]:
people = [input().split() for i in range(int(input()))]

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F


In [370]:
print(*name_format(people), sep='\n')

Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


### Words Score

In [371]:
import re

In [376]:
words = []
n = int(input())
words = input().split(' ')

3
programming is awesome


In [381]:
def score_words(words):
    vowels = 'aeiouy'
    count = 0
    for word in words:
        vowel_list = re.findall(f'[{vowels}]', word, re.I)
        if len(vowel_list)%2 == 0:
            count += 2
        else:
            count += 1
    return count

In [383]:
print(score_words(words))

4


### Arrays

In [384]:
import numpy

In [395]:
def arrays(arr):
    return numpy.array(arr[::-1], float)

In [396]:
arr = input().strip().split(' ')

1 2 3 4 -8 -10


In [398]:
result = arrays(arr)
print(result)

[-10.  -8.   4.   3.   2.   1.]


### Shape and Reshape

In [399]:
import numpy

In [400]:
array = list(map(int, input().split(' ')))

1 2 3 4 5 6 7 8 9


In [401]:
print(numpy.reshape(array, (3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Transpose and Flatten

In [402]:
import numpy

In [413]:
N, M = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(N)], int)

2 2
1 2
3 4


In [414]:
print(array.transpose())
print(array.flatten())

[[1 3]
 [2 4]]
[1 2 3 4]


### Concatenate

In [415]:
import numpy

In [416]:
N, M, P = map(int, input().split())
array1 = numpy.array([input().strip().split() for _ in range(N)], int)
array2 = numpy.array([input().strip().split() for _ in range(M)], int)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
3 4


In [419]:
print(numpy.concatenate((array1, array2), axis = 0))

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]
 [3 4]]


### Zeros and Ones

In [420]:
import numpy

In [421]:
dimensions = tuple(map(int, input().split()))

3 3 3


In [425]:
print(numpy.zeros(dimensions, dtype = numpy.int64))
print(numpy.ones(dimensions, dtype = numpy.int64))

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


### Eye and Identity

In [427]:
import numpy
numpy.set_printoptions(legacy='1.13')

In [428]:
N, M = map(int, input().split())

3 3


In [429]:
print(numpy.eye(N, M, k = 0))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Array Mathematics

In [430]:
import numpy

In [434]:
N, M = map(int, input().split())
A = numpy.array([input().strip().split() for _ in range(N)], int)
B = numpy.array([input().strip().split() for _ in range(N)], int)

1 4
1 2 3 4
5 6 7 8


In [438]:
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### Floor, Ceil and Rint

In [443]:
import numpy
numpy.set_printoptions(legacy='1.13')

In [444]:
A = list(map(float, input().split()))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


In [445]:
print(numpy.floor(A))
print(numpy.ceil(A))
print(numpy.rint(A))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### Sum and Prod

In [446]:
import numpy

In [447]:
N, M = map(int, input().split())
array1 = numpy.array([input().strip().split() for _ in range(N)], int)

2 2
1 2
3 4


In [449]:
sum_arr = numpy.sum(array1, axis = 0)
print(numpy.prod(sum_arr))

24


### Min and Max

In [450]:
import numpy

In [451]:
N, M = map(int, input().split())
array1 = numpy.array([input().strip().split() for _ in range(N)], int)

4 2
2 5
3 7
1 3
4 0


In [453]:
min_arr = numpy.min(array1, axis = 1)
print(numpy.max(min_arr))

3


### Mean, Var, and Std

In [454]:
import numpy

In [469]:
N, M = map(int, input().split())
a = numpy.array([input().strip().split() for _ in range(N)], float)

2 2
1 2
3 3


In [471]:
print(numpy.mean(a, axis = 1))
print(numpy.var(a, axis = 0))
print(numpy.around(numpy.std(a, axis = None), 11))

[ 1.5  3. ]
[ 1.    0.25]
0.82915619759


### Dot and Cross

In [472]:
import numpy

In [474]:
N = int(input())
A = numpy.array([input().strip().split() for _ in range(N)], int)
B = numpy.array([input().strip().split() for _ in range(N)], int)

2
1 2
3 4
1 2
3 4


In [482]:
matrix = []
for r in range(N):
    row = [numpy.dot(A[r,:],B[:,i]) for i in range(N)]
    matrix.append(row)

matrix = numpy.array(matrix)
print(matrix)

[[ 7 10]
 [15 22]]


### Inner and Outer

In [483]:
import numpy

In [491]:
A = numpy.array(input().strip().split(), int)
B = numpy.array(input().strip().split(), int)

0 1
2 3


In [492]:
print(numpy.inner(A, B))
print(numpy.outer(A, B))

3
[[0 0]
 [2 3]]


### Polynomials

In [493]:
import numpy

In [496]:
P = numpy.array(input().strip().split(), float)
x = float(input().strip())

1.1 2 3
0


In [497]:
print(numpy.polyval(P, x))

3.0


### Linear Algebra

In [498]:
import numpy

In [500]:
N = int(input())
A = numpy.array([input().strip().split() for _ in range(N)], float)

2
1.1 1.1
1.1 1.1


In [503]:
print(numpy.around((numpy.linalg.det(A)), 2))

0.0
